### ISSUE TITLE
Multiline Programs Aren't Working

### ISSUE THREAD

**Issue by Zachary-Rude** [yzyzsun/PyJS#1] opened 2021-06-25 15:46 UTC
When I write a program with multiple lines of code, I *always* get an error! The error shows the program as a *single*-line program, even though it is _actually_ a *multiline* program. What causes this, and how do I fix it?

**Comment by yzyzsun** [comment] 2021-06-25 17:22
I have just checked that multi-line Python programs should work. How did you use PyJS (as a library or via a CLI)? And what error did you get?

**Comment by Zachary-Rude** [comment] 2021-06-25 17:53
Well, I got syntax errors. I used PyJS in the demo.

**Comment by yzyzsun** [comment] 2021-06-25 17:58
Could you provide an example?

**Comment by yzyzsun** [comment] 2021-06-27 12:38
I'm closing this issue because it cannot be reproduced. Feel free to reopen it if you have a concrete example.

**Closed as completed by yzyzsun** 2021-06-27 12:38 UTC
